version: '3.7'
services:
  code:
    image: debian:jessie
    volumes:
    - ../:/var/www

  postgresdata:
    image: debian:jessie

  php:
    build: php
    image: php:7.2-fpm
    environment:
    - DEVELOPER_HOST=80.10.0.1
    - DEVELOPER_PORT=9000
    volumes:
    - ../:/var/www
    - code
    working_dir: /var/www
    links:
    - postgres
    - redis
    networks:
      jollyTeamProject:
        ipv4_address: 80.10.0.102

  nginx:
    build: nginx
    environment:
    - SERVER_NAME=localhost
    links:
    - php:fpm
    networks:
      jollyTeamProject:
        ipv4_address: 80.10.0.101
    ports:
    - "7010:80"
    volumes:
    - ../:/var/www
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    - code
    working_dir: /var/www

  postgres:
    image: postgres:11.1-alpine
    restart: always
    environment:
      POSTGRES_USER: 'dev'
      POSTGRES_PASSWORD: 'password'
    networks:
      jollyTeamProject:
        ipv4_address: 80.10.0.103
    ports:
    - '6060:5432'

  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080
    volumes:
    - postgres
    networks:
      jollyTeamProject:
        ipv4_address: 80.10.0.106

  redis:
    image: redis:3.2.11
    networks:
      jollyTeamProject:
        ipv4_address: 80.10.0.104

networks:
  jollyTeamProject:
    driver: bridge
    ipam:
      config:
      - subnet: 80.10.0.0/24

volumes:
  code:
  postgres:
